// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwvthgaenxkwgzyezrxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dnRoZ2Flbnhrd2d6eWV6cnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTk3NDAsImV4cCI6MjA3MTQzNTc0MH0.qpvkNZcx8Qez7pyN8tWEzHF1DyJ_f97B0jPWop1aqa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});